### ISSUE TITLE
Add user token support

### ISSUE THREAD

**Issue by Suzamax** [getseabird/seabird#13]
Hello,

I've tried your app, seems promising, but my kubeconfigs have only a token for the user (it comes from Rancher though).

Your app only supports certificate, what it's okay but it would be nice to support every type of authentication.

Thanks!

**Comment by jgillich** [comment]
Added in 5c0aed77651a07c256eb8e46257d30da1b37e452

Please let me know if this doesn't work

**Comment by Suzamax** [comment]
Sorry, but adding the KubeConfig didn't work...

![image](https://github.com/getseabird/seabird/assets/10341605/dda9749c-7892-4a64-be7a-9b3d23ae4eec)

I'll attach a KubeConfig (omitting current data):

```yaml
apiVersion: v1
kind: Config
clusters:
    - name: "****-****-prod"
      cluster:
        server: "https://rancher.*****.es/k8s/clusters/c-2wwqc"
    - name: "****-****-prod-master2"
      cluster:
        server: "https://244.233.222.211:6443"
        certificate-authority-data: "LS0*******************************************************************Qo="
    - name: "****-****-prod-master1"
      cluster:
        server: "https://244.233.222.222:6443"
        certificate-authority-data: "LS0tLS1CRUdJTi********UtLS0tLQo="
    - name: "****-****-prod-master3-dr"
      cluster:
        server: "https://255.244.233.233:6443"
        certificate-authority-data: "LS0tLS1C***************************UNBVEUtLS0tLQo="
users:
    - name: "****-****-prod"
      user:
        token: "kubeconfig-u-szdrc.c-2wwqc:vspfl4grjm**************9ptr7nzxp2rp8glj6"
contexts:
    - name: "****-****-prod"
      context:
        user: "****-****-prod"
        cluster: "****-****-prod"
    - name: "****-****-prod-master2"
      context:
        user: "****-****-prod"
        cluster: "****-****-prod-master2"
    - name: "****-****-prod-master1"
      context:
        user: "****-****-prod"
        cluster: "****-****-prod-master1"
    - name: "****-****-prod-master3-dr"
      context:
        user: "****-****-prod"
        cluster: "****-****-prod-master3-dr"
current-context: "****-****-prod"



```
