### ISSUE TITLE
proxy support (teleport)

### ISSUE THREAD

**Issue by d3m1gd** [getseabird/seabird#37]
### Summary

Add a teleport proxy support. 
https://goteleport.com/docs/kubernetes-access/introduction/

### Motivation

Some k8s clusters are managed behind access restrictors, such as teleport.

### Proposal

Add proxy support, with support for dialogs, asking for user password, OTP, etc.

Example kube config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERT>
    server: https://tp.example.com:443
    tls-server-name: kube.tp.example.com
  name: teleport
contexts:
- context:
    cluster: teleport
    user: teleport-k8s.example.com
  name: teleport-k8s.example.com
current-context: teleport-k8s.example.com
kind: Config
preferences: {}
users:
- name: teleport-k8s.example.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=k8s.example.com
      - --teleport-cluster=teleport
      - --proxy=tp.example.com:443
      command: tsh
      env: null
      provideClusterInfo: false
```
