### ISSUE TITLE
Can't connect to EKS Cluster

### ISSUE THREAD

**Issue by Jonomir** [getseabird/seabird#49]
### Issue description

Hello, there seems to be a problem with getting tokens for my EKS cluster.

Here is the error message:

```
Cluster connection failed
failed to get API group resources: unable to retrieve the complete list of server APls: v1: Get "https://cluster_id.cluster_region.eks.amazonaws.com/api/V1": getting credentials: exec: executable aws not found
It looks like you are trying to use a client-go credential plugin that is not installed.
To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-
plugins
```

Here is an example of my kubeconfig that was generated with `aws eks update-kubeconfig --name cluster_name`

```yaml
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: ca_data
      server: https://cluster_id.cluster_region.eks.amazonaws.com
    name: arn:aws:eks:cluster_region:account_id:cluster/cluster_name
users:
  - name: arn:aws:eks:cluster_region:account_id:cluster/cluster_name
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - --region
          - cluster_region
          - eks
          - get-token
          - --cluster-name
          - cluster_name
          - --output
          - json
        env:
          - name: AWS_PROFILE
            value: profile_name
contexts:
  - context:
      cluster: arn:aws:eks:cluster_region:account_id:cluster/cluster_name
      user: arn:aws:eks:cluster_region:account_id:cluster/cluster_name
    name: cluster_name
```

seabird seems to not be able to find the aws cli installed via homebrew to retrieve the token.

awscli is in the $PATH by adding  `/opt/homebrew/bin/` to the path in .zshenv

### Steps to reproduce

Import kubeconfig with users.user.exec section.
Try to connect to cluster.

### System information

Seabird v0.1.1, awscli 2.15.22, Apple M1 Pro, Macos 14.3.1
