### ISSUE TITLE
Support connection using oidc-login (kubelogin)

### ISSUE THREAD

**Issue by gaeljw** [getseabird/seabird#53]
### Summary

When using a kubeconfig file that uses oidc-login to authenticate to the cluster, an error appears and we're unable to register the cluster.

Example of kubeconfig file:
```yaml
users:
- name: my-user-with-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://my-oidc-provider.mycompany.net
      - --oidc-client-id=xxx
      - --oidc-client-secret=xxx
      - --oidc-extra-scope="email"
      command: kubectl
```

Error in the Seabird UI:
![image](https://github.com/getseabird/seabird/assets/18280708/e37fc65b-0f72-4a14-ac6a-b1f7ff14029a)

### Motivation

Authentication to K8S clusters using OIDC and especially [oidc-login/kubelogin](https://github.com/int128/kubelogin).

### Proposal

N/A
